# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tds_peaklag_cpp <- function(x, y, starts, win, max_lag) {
    .Call(`_PhysioNetPhysiology_tds_peaklag_cpp`, x, y, starts, win, max_lag)
}

